### ISSUE TITLE
StaticEvaluator evaluates starting position as 50

### ISSUE THREAD

**Issue by khushit-shah** [superchessengine/sce#1]
- StaticEvaluator evaluates the starting position as 50
- This must be a bug. Because the position is symmetrical.

**Comment by deep3072** [comment]
It seems there is some formula mistake of KING_WHITE_INC[] on Line 66 in `StaticEvaluator.cpp`. Though for all black pieces we can get by (64 - (i+1)) th index which I think would be more simpler.

**Comment by khushit-shah** [comment]
@deep3072  Yes, nice catch!
`64  - (i + 1)` wont work as it reverses the philes (a1 maps to h8)
the formula should be `(7-i/8)*8 + i % 8`, we are getting the rank using `i/8`, than flipping the rank, then the phile should be the same so adding `i % 8`

**Comment by deep3072** [comment]
Oh, Okay.
